# Generated by Django 4.0.4 on 2022-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
