# Generated by Django 4.0.4 on 2022-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_profile_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pictures',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
